export const OBSTACLE_WIDTH = 50;
export const OBSTACLE_GAP = 200;
export const GRAVITY = 5;
export const BIRD_WIDTH = 60;
export const BIRD_HEIGHT = 60;
export const BIRD_HEIGHT_HALF = BIRD_HEIGHT / 2;
export const BIRD_WIDTH_HALF = BIRD_WIDTH / 2;
export const CAP_WIDTH = 80;
export const CAP_HEIGHT = 30;
