export const OBSTACLE_WIDTH = 5;
export const OBSTACLE_GAP = 25;
export const GRAVITY = 1;
export const BIRD_WIDTH_IN_PX = 60;
export const BIRD_HEIGHT_IN_PX = 60;
export const BIRD_WIDTH = 6;
export const BIRD_HEIGHT = 6;
export const BIRD_HEIGHT_HALF = BIRD_HEIGHT / 2;
export const BIRD_WIDTH_HALF = BIRD_WIDTH / 2;
export const CAP_WIDTH = 8;
export const CAP_HEIGHT = 3;
export const GAME_SCREEN_SKY_CONTAINER = 80; //in vh
